apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "our-map-config-maps.fullname" . }}-server
  labels:
    {{- include "our-map-config-maps.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
data:
  application.properties: |-
    {{ .Files.Get .Values.applicationPropertiesPath | b64enc }}
