apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "our-map-config-maps.fullname" . }}-frontend
  labels:
    {{- include "our-map-config-maps.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
data:
  config.js: |-
    {{ .Files.Get .Values.configJsPath | b64enc }}
