apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "our-map-config-maps.fullname" . }}-frontend
  labels:
    {{- include "our-map-config-maps.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
data:
  # .js file은 그냥 넣으면 error converting YAML to JSON: yaml: line 16: did not find expected key 에러가 나서,
  # base64 encoding을 해서 pod에 마운팅한 뒤 pod lifecycle hook에서 base64 decoding을 해준다.
  config.js: |-
    {{ .Files.Get .Values.configJsPath | b64enc }}
