apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "our-map-server.fullname" . }}
  labels:
    {{- include "our-map-server.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "our-map-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "our-map-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: secret
            mountPath: /app/conf
            readOnly: true
          env:
          - name: OUR_MAP_OVERRIDING_PROPERTIES_FILENAME
            value: /app/conf/application.properties
          - name: JAVA_OPTS
            value: -Xmx120m
      volumes:
      - name: secret
        secret:
          secretName: our-map-secrets-server
