apiVersion: v1
kind: Secret
metadata:
  name: {{ include "our-map-secrets.fullname" . }}-frontend
  labels:
    {{- include "our-map-secrets.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  config.js: |-
    {{ .Files.Get .Values.configJsPath | b64enc }}
