apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "our-map-server-admin.fullname" . }}
  labels:
    {{- include "our-map-server-admin.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "our-map-server-admin.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        {{- include "our-map-server-admin.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: config
            mountPath: /app/conf
            readOnly: true
          - name: secret
            mountPath: /app/secret
            readOnly: true
          env:
          - name: OUR_MAP_OVERRIDING_PROPERTIES_FILENAMES
            value: /app/conf/application.properties,/app/secret/secret.properties
          - name: JAVA_OPTS
            value: -Xmx120m
      volumes:
      - name: config
        configMap:
          name: our-map-config-maps-server
      - name: secret
        secret:
          secretName: our-map-secrets-server
