name: GitHub Actions Demo
on: [push]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CI for branch [{{ github.ref }}] started"
      - run: echo "Clone repository and checkout to the target branch"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "Run gradle check"
      - run: ./gradlew check
