name: CI/CD
on:
  push:
    paths:
      - deploy/**
      - frontend-admin/**
      - subprojects/**
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CI for branch [{{ github.ref }}] started"
      - run: echo "Clone repository and checkout to the target branch"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "Set java version to 8"
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - run: echo "Run gradle check"
      - run: ./gradlew check
      - run: echo "Upload test result"
      - name: Upload test result
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-result
          path: |
            subprojects/our-map/build/reports/tests
            subprojects/our-map-server/build/reports/tests

      - run: echo "Configure AWS credentials"
        if: github.ref == 'refs/heads/main'
      - name: Configure AWS Credentials
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - run: echo "Push server docker image to ECR"
        if: github.ref == 'refs/heads/main'
      - run: ./deploy/docker-push.sh
        if: github.ref == 'refs/heads/main'
      - run: echo "Push frontend docker image to ECR"
        if: github.ref == 'refs/heads/main'
      - run: ./deploy/docker-push-frontend.sh
        if: github.ref == 'refs/heads/main'
# TODO: EKS 클러스터에 배포하기
